//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyExpenditure
    {
        public int ExpID { get; set; }
        public string Item { get; set; }
        public Nullable<System.DateTime> DateBought { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> UserId { get; set; }
        public string SharedWith { get; set; }
        public Nullable<bool> SharedWithMe { get; set; }
    
        public virtual SplitwiseUser SplitwiseUser { get; set; }
    }
}
