//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SplitwiseUser
    {
        public SplitwiseUser()
        {
            this.MonthlyExpenditure = new HashSet<MonthlyExpenditure>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> UserRole { get; set; }
    
        public virtual SplitWiseUserRoles SplitWiseUserRoles { get; set; }
        public virtual ICollection<MonthlyExpenditure> MonthlyExpenditure { get; set; }
    }
}
