//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SplitWiseUserRoles
    {
        public SplitWiseUserRoles()
        {
            this.SplitwiseUser = new HashSet<SplitwiseUser>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<SplitwiseUser> SplitwiseUser { get; set; }
    }
}
